language: python
python:
  - "3.7"
services:
  - docker

before_install:
  - docker pull natcap/pygeoprocessing-env:dev
  - docker run -it -v %CD%:/usr/local/pygeoprocessing natcap/pygeoprocessing-env:dev /bin/bash -ic "pip install -r requirements.txt && python setup.py install"


script:
- pytest -xv tests
