language: python

os: linux

services:
  - docker

before_install:
  - docker pull natcap/pygeoprocessing-env:dev

script:
  - docker run -it -v `pwd`:/usr/local/pygeoprocessing natcap/pygeoprocessing-env:dev "/bin/bash -ic 'pip install -r requirements.txt && python setup.py install && pytest -xv tests'"
