language: python

os: linux

services:
  - docker

install:
  - docker pull natcap/pygeoprocessing-test:dev

script:
  - docker run -it --rm -v `pwd`:/usr/local/pygeoprocessing natcap/pygeoprocessing-test:dev
