language: python

os: linux

services:
  - docker

before_install:
  - docker pull natcap/pygeoprocessing-env:dev

script:
  - echo "pip install -r requirements.txt" > runit.sh
  - echo "python setup.py install" >> runit.sh
  - echo "pytest -xv tests" >> runit.sh
