# Adapted from https://packaging.python.org/guides/supporting-windows-using-appveyor/
#
image: "Visual Studio 2015"

skip_non_tags: false  # we want to build untagged revisions.

environment:
  GCLOUD_WHLS: "https://storage.googleapis.com/natcap-build-dependencies/python-win32"
  PIP_INSTALL: "pip install --extra-index-url pypi.naturalcapitalproject.org --tristed-host pypi.naturalcapitalproject.org"

  matrix:
    # For Python versions available on Appveyor, see
    # https://www.appveyor.com/docs/windows-images-software/#python

    - PYTHON: "C:\\Python27"
      TOXENV: "py27"

    - PYTHON: "C:\\Python36"
      TOXENV: "py36"

    - PYTHON: "C:\\Python37"
      TOXENV: "py37"

    - PYTHON: "C:\\Python27-x64"
      TOXENV: "py27"

    - PYTHON: "C:\\Python36-x64"
      TOXENV: "py36"

    - PYTHON: "C:\\Python37-x64"
      TOXENV: "py37"

install:
    # We need wheel installed to build wheels
    - "%PYTHON%\\python.exe -m pip install --upgrade pip"
    - "%PYTHON%\\python.exe -m %PIP_INSTALL% gdal shapely rtree tox wheel -r requirements.txt"
    - "%PYTHON%\\python.exe setup.py install"

build: off

test_script:
    - "%PYTHON%\\python.exe -m tox -vv --sitepackages -e %TOXENV%"

after_test:
    # This step builds your wheels for artifacts
    - "%PYTHON%\\python.exe setup.py bdist_wheel"

artifacts:
    # bdist_wheel puts your built wheel in the dist directory
    - path: dist\*

# Cache-related items adapted from pyinstaller appveyor configuration.
# https://github.com/pyinstaller/pyinstaller/blob/develop/appveyor.yml
cache:
  # Cache downloaded pip, pipwin packages and built wheels.
  - '%LOCALAPPDATA%\pip\Cache\http'
  - '%LOCALAPPDATA%\pip\Cache\wheels'
  - '%HOMEPATH%\pipwin'

on_finish:
  # Remove old or huge cache files to hopefully not exceed the 1GB cache limit.
  #
  # If the cache limit is reached, the cache will not be updated (of not even
  # created in the first run). So this is a trade of between keeping the cache
  # current and having a cache at all.
  - C:\cygwin\bin\find "%LOCALAPPDATA%\pip" -type f -mtime +360 -delete
  - C:\cygwin\bin\find "%LOCALAPPDATA%\pip" -empty -delete
  # Show size of cache
  - C:\cygwin\bin\du -hs "%LOCALAPPDATA%\pip\Cache"
