# Adapted from https://packaging.python.org/guides/supporting-windows-using-appveyor/

skip_non_tags: false  # we want to build untagged revisions.

environment:
  matrix:
    # For Python versions available on Appveyor, see
    # https://www.appveyor.com/docs/windows-images-software/#python

    - PYTHON: "C:\\Python27"
      TOXENV: "py27"

    - PYTHON: "C:\\Python36"
      TOXENV: "py36"

    - PYTHON: "C:\\Python37"
      TOXENV: "py37"

    - PYTHON: "C:\\Python27-x64"
      TOXENV: "py27"

    - PYTHON: "C:\\Python36-x64"
      TOXENV: "py36"

    - PYTHON: "C:\\Python37-x64"
      TOXENV: "py37"

install:
    # We need wheel installed to build wheels
    - "%PYTHON%\\python.exe -m pip install wheel"
    - "%PYTHON%\\python.exe -m pip install pipwin"
    - "%PYTHON%\\python.exe -m pipwin install gdal"
    - "%PYTHON%\\python.exe -m pipwin install shapely"
    - "%PYTHON%\\python.exe -m pipwin install rtree"
    - "%PYTHON%\\python.exe -m pip install tox -r requirements.txt"

build: off

test_script:
    - "%PYTHON%\\python.exe -m tox --sitepackages -e %TOXENV%"

after_test:
    # This step builds your wheels.
    - "%PYTHON%\\python.exe setup.py bdist_wheel"

artifacts:
    # bdist_wheel puts your built wheel in the dist directory
    - path: dist\*
