pipelines:
  custom:
    appveyor:
      - step:
          name: "Run AppVeyor test suite"
          image: debian:9.7
          script:
            - apt-get update && apt-get install -y curl
            - |
              curl
              --header "Authorization: Bearer $APPVEYOR_API_KEY"
              --header "Content-Type: application/json"
              --data "{'accountName': '$APPVEYOR_ACC_NAME',
                       'projectSlug': '$APPVEYOR_PROJ_SLUG',
                       'branch': '$(hg branch)',
                       'commitID': '$(hg log -r . -T \"{node}\")'}"
            - echo "Build history at "
            - echo "    https://ci.appveyor.com/project/$APPVEYOR_ACC_NAME/$APPVEYOR_PROJ_SLUG/history"
  default:
    - parallel:
      - step:
          name: "Tests: python 2.7 on linux"
          image: natcap/py27-spatial-build:4b9b60f536fb6e7ad7adc7375d4f031e5b954bd1
          caches:
              - pip
          script:
              - pip install setuptools_scm cython tox
              - tox -e py27 --sitepackages
      - step:
          name: "Tests: python 3.6 on linux"
          image: natcap/py36-spatial-build:743e6fa5d57d9d84770414b69aab518490f24008
          caches:
              - pip
          script:
              - pip install setuptools_scm cython tox
              - tox -e py36 --sitepackages
      - step:
          name: "Tests: python 3.7 on linux"
          image: natcap/py37-spatial-build:5daac5b1d630949a2b81d1d0f8b017789a3bdeab
          caches:
              - pip
          script:
              - pip install setuptools_scm cython tox
              - tox -e py37 --sitepackages
      - step:
          name: "Tests: python 2.7 under WINE"
          image: natcap/py27-wine-build:f8dbb1a79151859d0358cc9e645d339bae5b992d
          caches:
              - pip
          script:
              - export WINEDEBUG=fixme-all  # Filter out fixme logging from WINE.
              - wine pip install cython numpy
              - wine tox -e py27 --sitepackages
