pipelines:
  default:
    - parallel:
      - step:
          name: Tests
          image: debian:stretch
          script:
            - apt-get update
            - apt-get install -y python{,3}-gdal python{,3}-numpy python{3,}-scipy python{,3}-shapely python{3}-rtree cython{,3}
            - tox
