pipelines:
  default:
    - parallel:
      - step:
          name: Tests on Python 2.7
          image: natcap/py27-spatial-build
          script:
            - pip install setuptools_scm cython tox
            - tox -e py27 --sitepackages
      - step:
          name: Tests on Python 3.6
          image: natcap/py36-spatial-build
          script:
            - pip install setuptools_scm cython tox
            - tox -e py36 --sitepackages
