name: PR changes on master into release branches
env:
    SOURCE_BRANCH: feature/auto-pr-on-commit-to-master
on:
    # This workflow should trigger when changes are pushed to master.
    # We expect this will happen when PRs into master are merged and also as
    # part of the automated bugfix release process.
    push:
        branches:
            - feature/auto-pr-on-commit-to-master

jobs:
    create-pr:
        name: PR master into release/**
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0
            - run: git fetch origin +refs/tags/*:refs/tags/*

            # Needed for envsubst
            - run: sudo apt-get update && sudo apt-get install gettext-base

            - name: Open a PR into each open release branch
              shell: bash
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  set -x
                  BRANCHES=$(git ls-remote --heads origin | grep release | cut -d '/' -f 3-)
                  echo $BRANCHES  # debugging
                  for RELEASE_BRANCH in `echo $BRANCHES`
                  do
                      PR_BODY_FILE=pr_body.txt
                      envsubst ci/bugfix-release-pr-body.md > $PR_BODY_FILE
                      cat $PR_BODY_FILE  # for debugging

                      hub pull-request \
                          --base $GITHUB_REPOSITORY:$SOURCE_BRANCH \
                          --head $GITHUB_REPOSITORY:$RELEASE_BRANCH \
                          --reviewer "natcap/software-team" \
                          --assign "natcap/software-team" \
                          --file $PR_BODY_FILE
                  done
