name: Build wheels
on: [push, pull_request]
jobs:
    build-wheels:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                python-version: [3.6, 3.7, 3.8]
                python-arch: [x64]
                os: [ubuntu-latest, windows-latest, macos-latest]
                include:
                    - python-version: 3.6
                      numpy: "numpy~=1.14"

                    - python-version: 3.7
                      numpy: "numpy~=1.15"

                    - python-version: 3.8
                      numpy: "numpy~=1.17"

                    - os: windows-latest
                      python-arch: x86

        steps:
            - uses: actions/checkout@v1

            - name: Set up python ${{ matrix.python-version }} ${{ matrix.python-arch }}
              uses: actions/setup-python@v1
              with:
                  python-version: ${{ matrix.python-version }}
                  architecture: ${{ matrix.python-arch }}

            - name: Install dependencie
              run: python -m pip install ${{ matrix.numpy }} cibuildwheel setuptools_scm cython

            - name: Build wheel
              run: python -m cibuildwheel --output-dir=wheelhouse

            - uses: actions/upload-artifact@v1
              with:
                  name: Wheel for ${{ matrix.os }} ${{ matrix.python-version }} ${{ matrix.python-arch }}
                  path: wheelhouse
