name: Test PyGeoprocessing

on: [push, pull_request]

jobs:
  Test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7]
        os: [ubuntu-16.04, windows-latest, macos-latest]
        env:
            - GDAL: "gdal>=2.2,<3"

    steps:
    - uses: actions/checkout@v1
    - name: setup-conda
      uses: s-weigand/setup-conda@v1.0.0
      with:
        update-conda: false
        python-version: ${{ matrix.python-version }}
        conda-channels: defaults
    - name: Install dependencies
      shell: bash
      env: ${{ matrix.env }}
      run: |
          conda install -y $GDAL shapely numpy scipy shapely cython rtree pytest
          conda upgrade -y pip setuptools

    - name: Install PyGeoprocessing (Mac)
      if: matrix.os == 'macos-latest'
      shell: bash
      run: CFLAGS="-stdlib=libc++ -mmacosx-version-min=10.9" python setup.py install

    - name: Install PyGeoprocessing (Windows)
      if: matrix.os == 'windows-latest'
      shell: cmd
      # Replace numpy and scipy with PyPI versions to circumvent import issue.
      # https://stackoverflow.com/a/37110747/299084
      run: |
          pip install --upgrade numpy scipy
          python setup.py install

    - name: Install PyGeoprocessing (Linux)
      if: matrix.os == 'ubuntu-16.04'
      run: |
          python setup.py install

    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: pytest
